from __future__ import annotations

import unittest

from plutchik_wave import PlutchikWaveSystem


class HelixParityTests(unittest.TestCase):
    """Golden values generated by Helix-AGI commit c599233."""

    def test_three_cycle_golden_trace(self) -> None:
        sequence = [
            (
                {"omega": 0.8, "H": 0.2, "D_KL": 0.1, "T": 1.0, "s_total": 0.2},
                ["m1"],
                0,
            ),
            (
                {"omega": 0.65, "H": 0.7, "D_KL": 0.4, "T": 1.3, "s_total": 0.5},
                ["m1", "m2"],
                2,
            ),
            (
                {"omega": 0.3, "H": 1.2, "D_KL": 1.8, "T": 1.8, "s_total": 0.9},
                ["m2"],
                5,
            ),
        ]
        expected = [
            {
                "position": [
                    0.8,
                    0.9,
                    0.012,
                    0.0,
                    0.0,
                    0.0,
                    0.029171449087032737,
                    0.05,
                ],
                "amplitude": 0.2949150351861777,
                "field_intensity": 0.2943843473578523,
                "steering": [
                    0.8,
                    0.9,
                    0.012,
                    0.0,
                    0.0,
                    0.0,
                    0.029171449087032737,
                    0.05,
                ],
                "dominant": "anticipation",
                "diversity": 0.0,
                "reactivation": 0.0,
            },
            {
                "position": [0.65, 0.6, 1.0, 1.0, 1.0, 0.2, 0.1485759102974077, 0.26],
                "amplitude": 0.9540033466694351,
                "field_intensity": 0.41816421866956877,
                "steering": [
                    0.650159805546874,
                    0.6003196110937481,
                    0.9989474141312561,
                    0.9989346296875061,
                    0.9989346296875061,
                    0.19978692593750125,
                    0.14844870032925483,
                    0.2597762722343763,
                ],
                "dominant": "fear",
                "diversity": 0.3948168139433966,
                "reactivation": 0.41816421866956877,
            },
            {
                "position": [0.3, 0.0, 1.0, 1.0, 1.0, 0.5, 0.44153612180399127, 1.0],
                "amplitude": 1.2783153299349446,
                "field_intensity": 0.28568749155732936,
                "steering": [
                    0.5251005213481083,
                    0.38588745966542,
                    0.9999803668570906,
                    0.9999801283978651,
                    0.9999801283978651,
                    0.30705527658718323,
                    0.253120540171561,
                    0.5240753125356569,
                ],
                "dominant": "fear",
                "diversity": 0.6588649259436502,
                "reactivation": 0.0,
            },
        ]

        field = PlutchikWaveSystem()
        for index, (snapshot, anchors, stagnation) in enumerate(sequence):
            payload = field.step_lagrangian(
                snapshot, anchor_ids=anchors, stagnation_counter=stagnation
            )
            result = payload["result"]
            packet = field.packets[-1]
            golden = expected[index]
            for actual, expected_value in zip(packet.position, golden["position"]):
                self.assertAlmostEqual(actual, expected_value, places=14)
            self.assertAlmostEqual(packet.amplitude, golden["amplitude"], places=14)
            self.assertAlmostEqual(
                result["field_intensity"], golden["field_intensity"], places=14
            )
            for actual, expected_value in zip(
                result["steering_vector"], golden["steering"]
            ):
                self.assertAlmostEqual(actual, expected_value, places=14)
            self.assertEqual(result["dominant_affect"], golden["dominant"])
            self.assertAlmostEqual(
                result["cognitive_diversity_signal"], golden["diversity"], places=14
            )
            self.assertAlmostEqual(
                result["reactivation_strength"], golden["reactivation"], places=14
            )


if __name__ == "__main__":
    unittest.main()
